# example config: configs/layout.yaml
output: { file: output/gds/layout.gds }

top_cells:
  - name: METASURFACE_CROSS
    layer: 1
    datatype: 0
    metasurfaces:
      - name: METASURFACE_CROSS_W_100_L_300_P_400
        origin: [0, 0]
        unit_cell:
          type: supercell
          cells: [{ type: cross, arm_length_um: 0.30, arm_width_um: 0.1, offset: [0.0, 0.0] }]
        lattice: { kind: square, pitch: 0.4, nx: 500, ny: 500 }
        aperture: { type: rectangle, width: 100, height: 100 }
  - name: METASURFACE_CYLINDER
    layer: 1
    datatype: 0
    metasurfaces:
      - name: METASURFACE_CYLINDER_R_150_P_400
        origin: [150, 0]
        unit_cell:
          type: supercell
          cells: [{ type: circle, radius_um: 0.15, offset: [0.0, 0.0] }]
        lattice: { kind: square, pitch: 0.4, nx: 500, ny: 500 }
        aperture: { type: rectangle, width: 100, height: 100 }